use std::fs;
use std::path::Path;

/// Auto-updater capability, emitted to capabilities/ only when the `updater`
/// Cargo feature is active. Gitignored so Flatpak/Snap builds (which disable
/// the feature) never reference permissions for plugins that aren't linked.
const AUTO_UPDATER_CAPABILITY: &str = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "auto-updater",
  "description": "Permissions for the in-app auto-updater (macOS + Linux AppImage). Generated by build.rs when the `updater` Cargo feature is enabled.",
  "windows": ["main", "miniplayer"],
  "permissions": [
    "updater:default",
    "process:allow-restart"
  ]
}
"#;

fn main() {
    let capability_path = Path::new("capabilities/auto-updater.json");

    if cfg!(feature = "updater") {
        if let Err(e) = fs::write(capability_path, AUTO_UPDATER_CAPABILITY) {
            panic!("Failed to emit auto-updater capability: {e}");
        }
    } else if capability_path.exists() {
        if let Err(e) = fs::remove_file(capability_path) {
            panic!("Failed to remove stale auto-updater capability: {e}");
        }
    }

    println!("cargo:rerun-if-changed=build.rs");

    tauri_build::build()
}
